# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo build first job
  - job: SecondJob
    steps:
    - bash: echo build second job
- stage: Devdeploy
  jobs:
  - job: Devdeploy
    steps:
    - bash: echo build Devdeploy
- stage: QAdeploy
  jobs:
  - job: QAdeploy
    steps:
    - bash: echo build QAdeploy
- stage: Proddeploy
  jobs:
  - job: Proddeploy
    steps:
    - bash: echo build Proddeploy

